import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { CssBaseline } from '@mui/material'

//TODO for create fonts configuration variable.
const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'iPlayed.games',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CssBaseline />
        {children}
      </body>
    </html>
  )
}
