import type { Metadata } from 'next'
import ThemeRegistry from '../contexts/themeRegistry/ThemeRegistry'
import { Footer, Header } from '@components'

export const metadata: Metadata = {
  title: 'iPlayed.games',
  //TODO: Change Meta
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Header />
          {children}
          {/* <Footer /> */}
        </ThemeRegistry>
      </body>
    </html>
  )
}
