name: FrontEnd CICD

on: [pull_request]

jobs:
  run-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Check tool versions
        run: |
          node -v
          npm -v
          aws --version
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Run typescript compiler, eslint and prettier
        run: npm run lint
      - name: Run unit test
        run: npm run test
